plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

collections:
  proekty:
    output: true
  portfolio:
    output: true
  lndwrk:
    output: true

social:
  name: –ê510
  links:
    - https://www.facebook.com/a510ru
    - http://instagram.com/a510ru
    - https://plus.google.com/111533556890655071026

logo: /images/logo2.svg
url: https://blok44.ru

title: ""
lang: "ru_RU"

defaults:
  -
    scope:
      path: ""
    values:
      image: /images/banners/dupleksy.jpg